### ISSUE TITLE
RegisterRunMethodsSequentially should have overload that provides `IServiceProvider`

### ISSUE THREAD

**Issue by daniel-white** [JonPSmith/RunStartupMethodsSequentially#4]
It is common for the register methods to have overloads that provide a `IServiceProvider`. `RegisterRunMethodsSequentially` should have this so that `IOptions<T>` can be used to configure the jobs.

**Comment by JonPSmith** [comment]
Hi @daniel-white,

I'm not that sure what you are asking.

- If you are asking how the startup service that are run within the global lock obtains the `IServiceProvider`, then the runner does that - see [this example](https://github.com/JonPSmith/RunStartupMethodsSequentially#2-creating-your-startup-services).
- If you are asking how the global lock methods obtains the `IServiceProvider`, then the `ILockAndRunJob` defines a method that contains the `IServiceProvider` - see [this example](https://github.com/JonPSmith/RunStartupMethodsSequentially/blob/main/RunMethodsSequentially/LockAndRunCode/SqlServerLockAndRunJob.cs).

**Comment by daniel-white** [comment]
for this extension method:

```
.RegisterRunMethodsSequentially(o =>
{
    // How to use DI to get the connection string...
    o.AddPostgreSqlLockAndRunMethods(connectionString);
});
```

my suggestion is to add an overload that supplies a `IServiceProvider`

```
.RegisterRunMethodsSequentially((sp, o) =>
{
    var options = sp.GetRequiredService<IOptions<Options>>();
    o.AddPostgreSqlLockAndRunMethods(options.Value.ConnectionString);
});
```

**Comment by JonPSmith** [comment]
Calling `GetRequiredService` during registering services (i.e. before you call `builder.Build()`) isn't recommended because it creates problems on singletons. The Microsoft docs says not to build temporary `IServiceProvider` while registering service but I can't find as this point. The recommended was is to use `builder.Configuration` to access the appsettings.json file, e.g. 

```c#
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
```
